# ---- METADATA ----
# Target: /etc/keyd/61.conf
# Author: Hentioe (绅士喵)
# CreatedAt: 2026-03-27
# UpdatedAt: 2026-03-29
# ---- METADATA ----

[ids]
# USB HID x3
352d:2380

[main]
capslock = overload(extend, capslock)
esc = overload(lfk_ext, esc)
rightalt = overload(alt, oneshot(double_ralt))
rightcontrol = overload(control, oneshot(double_rctrl))

[extend]
# 模拟 61 键盘原生组合键
compose = pagedown
slash = pageup
# 模拟游戏方向键
a = left
s = down
d = right
w = up
# 退格/删除键两用
backspace = delete

[lfk_ext]
1 = f1
2 = f2
3 = f3

[double_rctrl]
rightcontrol = C-A-right

[double_ralt]
rightalt = C-A-left
