# ---- METADATA ----
# Target: /etc/keyd/61.conf
# Author: Hentioe (绅士喵)
# CreatedAt: 2026-03-27
# UpdatedAt: 2026-04-01
# ---- METADATA ----

[ids]
# USB HID x3
352d:2380

[global]
#chord_timeout = 50

[main]
# Caps 扩展层
capslock = overload(extend, oneshot(shift))
# Esc 扩展层
esc = overload(esc_extend, esc)
# Tab 扩展层
tab = overload(tab_extend, tab)
# 字母组合键退格
d+f = backspace
# 字母组合键删除
j+k = delete
# 波浪号
leftalt+tab = ~
# 反引号
leftalt+esc = `
# 插入：名称 <邮箱>
n+e = macro(Hentioe space <contact@hentioe.dev>)

[extend]
# 模拟游戏方向键
a = left
s = down
d = right
w = up
# 翻页操作
compose = pagedown
slash = pageup
# 退格/删除键两用
backspace = delete
# 右功能键
minus = f11
equal = f12
# 复制
c = macro( C-c )
# 剪切
x = macro( C-x )
# 粘贴
v = macro( C-v )
# 撤销
z = macro( C-z )
# 生成引号对
apostrophe = macro( " " left )
# 生成括号对
9 = macro( ( ) left )
# 生成中括号对
[ = macro( [ ] left )

[esc_extend]
# 左功能键
1 = f1
2 = f2
3 = f3

[tab_extend]
# KDE 工作区切换
q = macro( C-A-left )
e = macro( C-A-right )

