# ---- METADATA ----
# Target: /etc/keyd/61.conf
# Author: Hentioe (绅士喵)
# CreatedAt: 2026-03-27
# UpdatedAt: 2026-03-31
# ---- METADATA ----

[ids]
# USB HID x3
352d:2380

[global]
#chord_timeout = 50

[main]
# 扩展层
capslock = overload(extend, oneshot(shift))
# 左功能键（F1-F3）
esc = overload(left_fkeys, esc)
# KDE 工作区双击切换
rightalt = overload(alt, oneshot(double_ralt))
rightcontrol = overload(control, oneshot(double_rctrl))
# 字母组合键退格
d+f = backspace
# 字母组合键删除
j+k = delete
# 插入：名称 <邮箱>
n+e = macro(Hentioe space <contact@hentioe.dev>)

[extend]
# 模拟游戏方向键
a = left
s = down
d = right
w = up
# 翻页操作
compose = pagedown
slash = pageup
# 退格/删除键两用
backspace = delete
# 生成引号对
apostrophe = macro( " " left )
# 生成括号对
9 = macro( ( ) left )
# 生成中括号对
[ = macro( [ ] left )

[left_fkeys]
1 = f1
2 = f2
3 = f3

[double_rctrl]
rightcontrol = C-A-right

[double_ralt]
rightalt = C-A-left

