# ---- METADATA ----
# Target: ~/.config/neovide/config.toml
# Author: Hentioe (绅士喵)
# CreatedAt: 2024-06-24
# UpdatedAt: 2024-06-24
# ---- METADATA ----

[font]
normal = ["Noto Sans Mono CJK SC"]
size = 13
